j100_0000:
  diagnostic_aggregator:
    ros__parameters:
      path: 'Clearpath Diagnostics'
      platform.type: 'diagnostic_aggregator/AnalyzerGroup'
      platform.path: 'Platform'
      platform.analyzers.power.type: 'diagnostic_aggregator/GenericAnalyzer'
      platform.analyzers.power.path: 'Power'
      platform.analyzers.power.expected: ['clearpath_diagnostic_updater: Battery Management System', 'clearpath_diagnostic_updater: Power Status']
      platform.analyzers.power.contains: ['Battery', 'Power']
      platform.analyzers.stop_status.type: 'diagnostic_aggregator/GenericAnalyzer'
      platform.analyzers.stop_status.path: 'E-stop Status'
      platform.analyzers.stop_status.expected: ['clearpath_diagnostic_updater: E-stop Status']
      platform.analyzers.stop_status.contains: ['E-stop']
      platform.analyzers.drive.type: 'diagnostic_aggregator/GenericAnalyzer'
      platform.analyzers.drive.path: 'Drive System'
      platform.analyzers.drive.expected: ['controller_manager: Controller Manager Activity', 'controller_manager: Controllers Activity', 'controller_manager: Hardware Components Activity']
      platform.analyzers.drive.contains: ['lynx', 'puma', 'sevcon', 'controller_manager', 'twist_mux', 'joy_node']
      use_sim_time: True
      platform.analyzers.mcu.type: 'diagnostic_aggregator/GenericAnalyzer'
      platform.analyzers.mcu.path: 'MCU'
      platform.analyzers.mcu.expected: ['clearpath_diagnostic_updater: MCU Firmware Version', 'clearpath_diagnostic_updater: MCU Status']
      platform.analyzers.mcu.contains: ['MCU']
      platform.analyzers.odometry.type: 'diagnostic_aggregator/GenericAnalyzer'
      platform.analyzers.odometry.path: 'Odometry'
      platform.analyzers.odometry.contains: ['odometry', 'ekf_node']
      platform.analyzers.odometry.expected: ['ekf_node: Filter diagnostic updater', 'ekf_node: odometry/filtered topic status']
      platform.analyzers.networking.type: 'diagnostic_aggregator/GenericAnalyzer'
      platform.analyzers.networking.path: 'Networking'
      platform.analyzers.networking.contains: ['Wi-Fi']
      platform.analyzers.networking.expected: ['wireless_watcher: Wi-Fi Monitor']
      sensors.type: 'diagnostic_aggregator/AnalyzerGroup'
      sensors.path: 'Sensors'
      sensors.analyzers.imu.type: 'diagnostic_aggregator/GenericAnalyzer'
      sensors.analyzers.imu.path: 'IMU'
      sensors.analyzers.imu.contains: ['imu']
      sensors.analyzers.gps.type: 'diagnostic_aggregator/GenericAnalyzer'
      sensors.analyzers.gps.path: 'GPS'
      sensors.analyzers.gps.contains: ['gps']
      sensors.analyzers.cameras.type: 'diagnostic_aggregator/GenericAnalyzer'
      sensors.analyzers.cameras.path: 'Cameras'
      sensors.analyzers.cameras.contains: ['camera']
