j100_0000:
  clearpath_diagnostic_updater:
    ros__parameters:
      serial_number: 'j100-0000'
      platform_model: 'j100'
      ros_distro: 'jazzy'
      latest_apt_firmware_version: 'simulated'
      installed_apt_firmware_version: 'simulated'
      use_sim_time: True
      bms_state_rate: 10.0
      bms_state_tolerance: 0.15
      topics.sensors/imu_0/data.type: 'sensor_msgs/msg/Imu'
      topics.sensors/imu_0/data.rate: 50.0
      topics.sensors/gps_0/fix.type: 'sensor_msgs/msg/NavSatFix'
      topics.sensors/gps_0/fix.rate: 10.0
      topics.sensors/camera_0/color/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_0/color/image.rate: 30.0
      topics.sensors/camera_0/depth/image.type: 'sensor_msgs/msg/Image'
      topics.sensors/camera_0/depth/image.rate: 15.0
      topics.sensors/camera_0/points.type: 'sensor_msgs/msg/PointCloud2'
      topics.sensors/camera_0/points.rate: 15.0
