j100_0000:
  twist_mux:
    ros__parameters:
      use_stamped: True
      topics.joy.topic: 'joy_teleop/cmd_vel'
      topics.joy.timeout: 0.5
      topics.joy.priority: 10
      topics.interactive_marker.topic: 'twist_marker_server/cmd_vel'
      topics.interactive_marker.timeout: 0.5
      topics.interactive_marker.priority: 8
      topics.rc.topic: 'rc_teleop/cmd_vel'
      topics.rc.timeout: 0.5
      topics.rc.priority: 12
      topics.external.topic: 'cmd_vel'
      topics.external.timeout: 0.5
      topics.external.priority: 1
      locks.e_stop.topic: 'platform/emergency_stop'
      locks.e_stop.timeout: 0.0
      locks.e_stop.priority: 255
      locks.safety_stop.topic: 'platform/safety_stop'
      locks.safety_stop.timeout: 0.0
      locks.safety_stop.priority: 254
      use_sim_time: True
